kind: Service
apiVersion: v1
metadata:
  name: ceph-exporter
  namespace: ceph
spec:
  selector:
    app: ceph-exporter
  type: NodePort  
  ports:
  - name: ceph-exporter
    nodePort: 30128
    port: 9128
    protocol: TCP
    targetPort: ceph-exporter
  selector:
    prometheus: ceph-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: ceph-exporter
  namespace: ceph
  labels:
    prometheus: ceph-exporter
spec:
  version: v1.3.0
  serviceMonitors:
  - selector:
      matchLabels:
        tier: ceph-exporter
