apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s-ceph-exporter
  namespace: monitoring
  labels:
    prometheus: k8s
spec:
  replicas: 1
  version: v2.1.0
  serviceAccountName: ceph-exporter
  serviceMonitorSelector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  resources:
    requests:
      memory: 2Gi
      cpu: 250m
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: ceph-exporter
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 5Gi
