apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ceph-exporter
  namespace: ceph
spec:
  selector:
    matchLabels:
      app: ceph-exporter
  endpoints:
  - port: ceph-exporter
    interval: 15s
